output-format: emacs

uses: django
max-line-length: 240
strictness: veryhigh

doc-warnings: false

pep8:
  full: true
  disable:
    - E127

pylint:
  disable:
    - cyclic-import                 # False-positives, and also seems to break other checks (?).
    - logging-format-interpolation  # We use .format()-style for string formatting. Aiming for fstring-style formatting later (but requires >=3.6, so not yet).
  options:
    variable-rgx: '[a-z_][a-z0-9_]{0,30}$'
    dummy-variables-rgx: _|dummy
    method-rgx: '[a-z_][a-z0-9_]{1,40}$'
    function-rgx: '[a-z_][a-z0-9_]{1,40}$'
    class-attribute-rgx: '([A-Za-z_][A-Za-z0-9_]{2,40}|(__.*__))$'

    max-module-lines: 1400
    max-public-methods: 31  # Changes class has 31. Please adapt after refactoring of Changes.
    min-public-methods: 0
    max-args: 10
    max-locals: 30
    max-attributes: 15

mccabe:
  options:
    max-complexity: 17

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D106
    - D107
    - D200
    - D202
    - D203
    - D204
    - D205
    - D207
    - D210
    - D212
    - D213
    - D300
    - D301
    - D400
    - D401
    - D403
    - D404
    - D412
    - D413
