#!/usr/bin/python3
# pylint: disable=invalid-name  # https://github.com/PyCQA/pylint/issues/516

from pprint import pprint

from mini_buildd.api.client_1_0 import Daemon

MBD = Daemon("localhost", "8066")

STATUS = MBD.call("status")

pprint(STATUS)
pprint(STATUS.repositories)
pprint(STATUS.chroots)
