#!/usr/bin/python
# -*- coding: utf-8 -*-
from pprint import pprint

from mini_buildd.api.client_1_0 import Daemon

MBD = Daemon("localhost", "8066")

STATUS = MBD.call("status")

pprint(STATUS)
pprint(STATUS.repositories)
pprint(STATUS.chroots)
