#!/usr/bin/python3 -W default

import sys
import importlib
import doctest

import mini_buildd.misc
import mini_buildd.api

mini_buildd.api.django_pseudo_configure()
mini_buildd.misc.setup_console_logging()

RESULT = doctest.testmod(importlib.import_module(sys.argv[1]), verbose=False)
sys.exit(RESULT.failed)
